# permissions for end users to edit oapservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oapserver-editor-role
rules:
- apiGroups:
  - operator.skywalking.apache.org
  resources:
  - oapservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.skywalking.apache.org
  resources:
  - oapservers/status
  verbs:
  - get
